<?php

const PAGINATION = 30; // 30 is Default
const PERMISSIONS = [
    'create target',
    'read target',
    'update target',
    'delete target',
    'create department',
    'read department',
    'update department',
    'delete department',
    'create product',
    'read product',
    'update product',
    'delete product',
    'create supplier',
    'read supplier',
    'update supplier',
    'delete supplier',
    'create purchase',
    'read purchase',
    'update purchase',
    'delete purchase',
    'read warehouse',
    'read warehouseTransaction',
    'create client',
    'read client',
    'update client',
    'delete client',
    'create eol',
    'read eol',
    'update eol',
    'delete eol',
    'create user',
    'read user',
    'update user',
    'delete user',
    'create role',
    'read role',
    'update role',
    'delete role',
    'create rent',
    'read rent',
    'update rent',
    'delete rent',
    'create party',
    'read party',
    'update party',
    'delete party',

    'create employee',
    'read employee',
    'update employee',
    'delete employee',

    'create safe',
    'read safe',
    'update safe',
    'delete safe',

    'create ft_type',
    'read ft_type',
    'update ft_type',
    'delete ft_type',

    'create ft',
    'read ft',
    'update ft',
    'delete ft',

    'read report',
];
